* 018: Secrets Database

The secrets database will be a two-level folder structure. The first
level will be folders that take on the name of the service that you
make accounts for. Having it as it's own folder rather than using
~nexp~ namespacing allows the use of full URLs like ~google.com~
rather than ~google~.

In each service folder no sub-folders are allowed. Each file in a
subfolder will represent a single account for the service.  File names
will follow ~rfc:salotz.004_nexps~ and need not contain the username
in the filename. File names should reflect a user's petname for the
account. Actual account names may be useful for this distinction.

Files shall have the format of the first line containing the main
secret which is usually the password. The rest of the file should be
in the TOML format and should contain at least a header section for
account information (~account~) that minimally should contain a user name
~username~ and/or an email ~email~ that serves as the account ID. Some
accounts require both, some only use emails. If this is the case use
the email as ~username~ and the email will be inferred. 

Example A email is username:

#+begin_src toml
  password

  [account]

  username = "my.email@mail.com"
  description = "My account for the forum site."
#+end_src

Example B separate username and email:

#+begin_src toml
  password

  [account]

  username = "hackzoorrz"
  email = "my.email@mail.com"
  description = "My account for the forum site."
#+end_src

Additional sections with their own schemas can be added depending on
the content. These should be described in separate RFCs.

