#+TODO: IDEA WIP | DRAFT | STABLE

* Request For Comments


** Proposals

*** IDEA 001: Written Document Format

Use org-mode markup.


*** WIP 002: Semantic Changelog

- nexp :: ~rfc:salotz.002_semantic-changelog.org~

Proposal: [[file:rfcs/salotz.002_semantic-changelog.org][file:./rfcs/salotz.002_semantic-changelog.org]]

Abstract:

#+begin_quote
A mini-format for git commit messages that supports machine
readability (without sacrificing human readability) semantic
expression of impacts of code change.
#+end_quote


*** WIP 003: RFC Specifications

- nexp :: ~rfc:salotz.003_rfc-specs~

Proposal: [[file:./rfcs/salotz.003_rfc-specs.org]]

Abstract:

#+begin_quote
Specifications for necessary information for an RFC and how to format
it.
#+end_quote




*** WIP 004: Name Expressions (nexps)

- nexp :: ~rfc:salotz.004_nexps~

Proposal: [[file:./salotz.004_nexps.org]]

Abstract:

#+begin_quote
A proposal that defines how to name digital document entities:
e.g. ~format:namespace.field-1_field-2~
#+end_quote




*** IDEA 005: Syxel Buffers Format

- nexp :: ~rfc:salotz.005_syxel-buffers~

Proposal: [[file:./rfcs/salotz.005_syxel-buffers.org]]

Abstract:

#+begin_quote
Format that utilizes a granular unit of 'syxel' (symbolic pixel) in a
rectangular plane similar to a pixel based image format. Syxels are
basically character points.
#+end_quote


*** WIP 006: Codetags

- nexp :: ~rfc:salotz.006_codetags~

Proposal: [[file:./rfcs/salotz.006_codetags.org]]

Abstract:

#+begin_quote
Tags that are added in comments to code that add semantic meaning to
otherwise freeform comments, making them searchable by machine and
available to tooling.
#+end_quote


*** IDEA 007: Python Library Repo Layout

- nexp :: ~rfc:salotz.007_py-lib-layout~

Proposal: [[file:./rfcs/salotz.007_py-lib-layout.org]]

Executive Summary:

#+begin_quote
A layout and content specification that follows best practices that
strives for effectiveness rather than complete compatibility.
#+end_quote


*** WIP 008: Linux Shell Startup Indirection Layer

- nexp :: ~rfc:salotz.008_linux-shell-startup~

Proposal: [[file:./rfcs/salotz.008_linux-shell-startup.org]]

Executive Summary:

#+begin_quote
A collection of script files which add a layer of indirection to
standard linux shells (i.e. POSIX ~sh~ and ~bash~) that allows for a
more modular, composable, and semantic organization.
#+end_quote


*** IDEA 009: Repo Layout Templates

- nexp :: ~rfc:salotz.009_repo-layout~

Proposal: [[file:./rfcs/salotz.009_repo-layout.org]]

Executive Summary:

#+begin_quote
A template format for generating and specifying repo layouts in
directories, i.e. cookiecutter.
#+end_quote


*** IDEA 010: Growth Mindset Versioning

- nexp :: ~rfc:010_growth-versioning~

Proposal: [[file:./rfcs/010_growth-versioning.org]]

Executive Summary:

#+begin_quote
Version formatting that doesn't lie.
#+end_quote




*** IDEA 011: Writetags

- nexp :: ~rfc:011_write-tags~

Proposal: [[file:./rfcs/011_write-tags.org]]

Executive Summary:

#+begin_quote
Tags (see [[*006: Codetags][rfc:salotz.006_codetags]] for a similar proposal) that are
added in comments to prose (documentation, whitepapers, technical
documents, etc.) that add semantic meaning to otherwise freeform
comments, making them searchable by machine and available to tooling.
#+end_quote


*** IDEA 012: Errors as Information

- nexp :: ~rfc:012_information-errors~

Proposal: [[file:./rfcs/012_information-errors.org]]

Executive Summary:

#+begin_quote
Errors in information systems, like event logs, should take on a role
of providing information rather than being categorized based on their
operational importance as is the case in most languages (e.g. checked
vs. unchecked exceptions). Inspired by Stuart Holloway and
specifically this talk: https://youtu.be/oOON--g1PyU?t=965
#+end_quote


*** IDEA 013: Code Targets

- nexp :: ~rfc:013_code-targets~

Proposal: [[file:./rfcs/013_code-targets.org]]

Executive Summary:

#+begin_quote
Code targets are a specification for a syntax which should be
recognized by metaprogramming tools like template engines, editors,
etc.
#+end_quote

*** IDEA 014: Project & Maintainence Intentions for OSS

- nexp :: ~rfc:014_project-intent~

Proposal: [[file:./rfcs/014_project-intent.org]]

Executive Summary:

#+begin_quote
A proposal for a best practice that includes a clear statement of
intent on open source projects that would allow for greater
understanding by consumers about the current state and intentions of
developers in fairly unambiguous terms. Extensions could provide
optional semantic vocabularies for very clear intent and to provide a
set of choices for developers so they don't have to think as much from
scratch.
#+end_quote


* Network

RFCs from around the net I support:

- You could be the first

* COMMENT Local variables

# Local Variables:
# mode: org
# org-todo-keyword-faces: (("IDEA" . "magenta") ("WIP" . "magenta") ("DRAFT" . "orange") ("STABLE" . org-done))
# End:


