#+TODO: IDEA WIP | DRAFT | STABLE

* Request For Comments


** Proposals

*** IDEA 001: Written Document Format

Use org-mode markup.


*** WIP 002: Semantic Changelog

- nexp :: ~rfc:salotz.002_semantic-changelog.org~

Proposal: [[file:rfcs/salotz.002_semantic-changelog.org][file:./rfcs/salotz.002_semantic-changelog.org]]

Executive summary:

#+begin_quote
A mini-format for git commit messages that supports machine
readability (without sacrificing human readability) semantic
expression of impacts of code change.
#+end_quote


*** WIP 003: RFC Specifications

- nexp :: ~rfc:salotz.003_rfc-specs~

Proposal: [[file:./rfcs/salotz.003_rfc-specs.org]]

Executive Summary:

#+begin_quote
Specifications for necessary information for an RFC and how to format
it.
#+end_quote




*** WIP 004: Name Expressions (nexps)

- nexp :: ~rfc:salotz.004_nexps~

Proposal: [[file:./salotz.004_nexps.org]]

Executive Summary:

#+begin_quote
A proposal that defines how to name digital document entities:
e.g. ~format:namespace.field-1_field-2~
#+end_quote




*** IDEA 005: Rectangular Character Buffers

- nexp :: ~rfc:salotz.005_rect-buffers~

Proposal: [[file:./rfcs/salotz.005_rect-buffers.org]]

Executive Summary:

#+begin_quote
Specification for a format and display protocol oriented around plane
text rectangles, rather than lines.
#+end_quote


* Network

RFCs from around the net I support:

- You could be the first

* COMMENT Local variables

# Local Variables:
# mode: org
# org-todo-keyword-faces: (("IDEA" . "magenta") ("WIP" . "magenta") ("DRAFT" . "orange") ("STABLE" . org-done))
# End:


